change-id = 132494

[build]
sanitizers = true
build-stage = 1
test-stage = 1
docs = false
tools = [
    "cargo",
    "clippy",
    "bsan",
    "rustfmt",
    "rust-analyzer",
    "rust-analyzer-proc-macro-srv",
    "analysis",
    "src",
    "miri", 
    "cargo-miri",
    "bsan"
]

[rust]
incremental = true
channel = "nightly"

[llvm]
download-ci-llvm = false
clang = true