name: build
on:
  pull_request:
    branches:
      - "bsan"
    paths:
      - '**/*.rs'
      - '**/*.toml'
      - '**/*.yml'
      - 'src/llvm-project'
  workflow_dispatch:

permissions:
  contents: read
defaults:
  run:
    shell: bash
concurrency:
  group: "build"
  cancel-in-progress: true
jobs:
  fmt:
    runs-on: macos-latest
    name: Formatting
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upstream
        run: src/ci/scripts/setup-upstream-remote.sh
      - name: Format
        run: ./x.py fmt --check
      - name: Clippy - bsan-cli
        run: ./x.py clippy src/tools/bsan/bsan-cli
      - name: Clippy - cargo-bsan
        run: ./x.py clippy src/tools/bsan/bsan-cli/cargo-bsan
      - name: Clippy - bsan-rt
        run: ./x.py clippy src/tools/bsan/bsan-rt
  build-linux:
    runs-on: ubuntu-latest
    name: Build (x86 Linux)
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
            sudo apt-get install ninja-build
            rustup component add llvm-tools-preview
            cp src/bootstrap/defaults/config.bsan.dev.toml config.toml
      - name: Upstream
        run: src/ci/scripts/setup-upstream-remote.sh
      - name: Build
        run: ./x.py build --stage 1
      - name: Clippy - bsan-cli
        run: ./x.py clippy src/tools/bsan/bsan-cli
      - name: Clippy - cargo-bsan
        run: ./x.py clippy src/tools/bsan/bsan-cli/cargo-bsan
      - name: Clippy - bsan-rt
        run: ./x.py clippy src/tools/bsan/bsan-rt
  build-macos:
    runs-on: macos-latest
    name: Build (ARM64 macOS)
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
            brew install ninja
            cp src/bootstrap/defaults/config.bsan.dev.toml config.toml
      - name: Upstream
        run: src/ci/scripts/setup-upstream-remote.sh
      - name: Stage 1 Build
        run: ./x.py build --stage 1 
      - name: Clippy - bsan-cli
        run: ./x.py clippy src/tools/bsan/bsan-cli
      - name: Clippy - cargo-bsan
        run: ./x.py clippy src/tools/bsan/bsan-cli/cargo-bsan
      - name: Clippy - bsan-rt
        run: ./x.py clippy src/tools/bsan/bsan-rt
