name: build
'on':
  pull_request:
    branches:
      - bsan
    paths:
      - '**/*.rs'
      - '**/*.toml'
      - '**/*.yml'
      - src/llvm-project
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: null
permissions:
  contents: read
defaults:
  run:
    shell: bash
concurrency:
  group: build
  cancel-in-progress: true
jobs:
  fmt:
    runs-on: macos-latest
    name: Formatting
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upstream
        run: src/ci/scripts/setup-upstream-remote.sh
      - name: Format
        run: ./x.py fmt --check
  build:
    needs: [fmt]
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: x86 Linux
            os: ubuntu-latest
          - arch: ARM64 macOS
            os: macos-latest
          - arch: ARM64 Linux
            os: ubuntu-24.04-arm
    runs-on: '${{ matrix.config.os }}'
    name: 'Build (${{ matrix.config.arch }})'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          rustup component add llvm-tools-preview
          cp src/bootstrap/defaults/config.bsan.dev.toml config.toml
      - name: Upstream
        run: src/ci/scripts/setup-upstream-remote.sh
      - name: Build
        run: ./x.py build --stage 1
      - name: Unit Tests
        run: ./x.py test --stage 1 src/tools/bsan/bsan-rt
      - name: UI Tests
        run: ./x.py test --stage 2 src/tools/bsan/bsan-driver
      