name: build
on:
  push:
    branches:
      - bsan
    paths:
      - '**/*.rs'
      - '**/*.toml'
      - 'src/llvm-project'
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read
defaults:
  run:
    shell: bash
concurrency:
  group: "build"
  cancel-in-progress: true
jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build (Linux)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
            sudo apt-get install ninja-build
            rustup component add llvm-tools-preview
      - name: Upstream
        run: src/ci/scripts/setup-upstream-remote.sh
      - name: Stage 1 Build
        run: ./x.py build --stage 1 --config src/bootstrap/defaults/config.bsan.dev.toml
  build-macos:
    runs-on: macos-latest
    name: Build (macOS)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
            brew install ninja
      - name: Upstream
        run: src/ci/scripts/setup-upstream-remote.sh
      - name: Stage 1 Build
        run: ./x.py build --stage 1 --config src/bootstrap/defaults/config.bsan.dev.toml