name: nightly
on: workflow_dispatch
permissions:
  contents: read
  pages: write
  id-token: write
defaults:
  run:
    shell: bash
concurrency:
  group: "sync"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install LLVM
        run: |
          sudo apt-get install llvm
      - name: Install ninja
        run: sudo apt-get install ninja-build
      - name: Install cargo binutils
        run: |
          rustup component add llvm-tools-preview
      - name: Rebase
        run: src/ci/scripts/sync.sh
      - name: Build
        run: ./x.py build --stage 1 library --set llvm.download-ci-llvm=false